#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright (C) 2021-23 Freie Universität Berlin
# Copyright (C) 2023-25 TU Dresden
#
# Distributed under terms of the MIT license.

# pylint: disable=invalid-name

import sys
from aiodnsprox.cli.proxy import sync_main


if __name__ == '__main__':
    sys.exit(sync_main())
